### ISSUE TITLE
Printing out of site

### ISSUE THREAD

**Issue by StakFallT** [l9c/tmux_cheat_sheet_data#15]
I'm not sure if this is the proper place for this since this repo seems more about the data https://tmuxcheatsheet.com/ uses than the site itself, but I know if one never asks, it definitely will never get done :P But as a more practical reason, it'd be great to be able to print out the sheet with the formatting as it is on the page so that it can be stored in like a binder on the desk with other cheat sheet-like references. For now, I know that screen captures and printing the images are a workaround. However, printing images means technically the white background of the page is actually "getting printed" (even if it's nothing) -- meaning, visually sure it may look the same but it's not actually the same. Additionally, it may use more up more memory spooling the print job. When printed to PDF, the print preview looks like this:

![tmuxcheatsheet com print preview - Screenshot_2024-07-19_08-15-25](https://github.com/user-attachments/assets/5be04a5e-238c-4fca-8ca3-a5de13f050e9)

Obviously, that's super not-helpful. I've looked around online a bit and many people reference (when dealing with print questions in general) creating a stylesheet with media=print or something, but the implementations I've seen using that require the file to be hosted somewhere and from what I understand, it can't be local, as the browser is sandboxed from being able to ingest anything on the local filesystem for security purposes. So unless there's a way to specify media=print and inline the thing so that it can be injected via developer tools, there doesn't seem to be an easy way to achieve printing the page and storing it in a nice physical reference manual to be put on the desk which is a pretty big bummer since I'm using tmux more and more over screen and byobu and consider tmux one of my best-of-breed tools in my overall tool / utility toolbox.

**Comment by l9c** [comment]
The cheat sheet is indeed designed for an interactive experience within web browsers. Since this issue has been raised before (#9 ), I'm currently reevaluating it.
Thank you for the feedback.

**Comment by StakFallT** [comment]
Awesome, thanks so much! I'm sorry I didn't search. I'm so used to repos having a bunch of different issues open, that when I saw nothing opened, I assumed (_incorrectly_) that the issue system for the repo didn't really get used.

I looked over #9 as you linked and it indeed is exactly the same request as mine (_not that I had any doubts -- I just wanted to do my due diligence and check the details of the previously made request :)_ ). It appears as though there was no follow up with respect to the suggested workaround (to hit ctrl+p to save as a PDF). Initially, I was going to say this issue could be closed and #9 left open, but #9 is closed and the workaround stated in #9, unfortunately, at least for me, results in the image I attached in my opened issue. So in a sense, the "issue" is still pending a resolution.

**Comment by l9c** [comment]
The site is now ready for printing.

**Comment by pzhlkj6612** [comment]
> The site is now ready for printing.

It works! However, Google's ads occupy some space on the paper. Is there a way to remove them when printing?

![The screenshot of Google Ads on the paper](https://github.com/user-attachments/assets/6190188c-a5ad-474d-aa20-796d6cae4b15)

.

**Comment by l9c** [comment]
> > The site is now ready for printing.
> 
> It works! However, Google's ads occupy some space on the paper. Is there a way to remove them when printing?
> 
> ![The screenshot of Google Ads on the paper](https://private-user-images.githubusercontent.com/29089388/352765945-6190188c-a5ad-474d-aa20-796d6cae4b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMzQ0MzUsIm5iZiI6MTcyMjIzNDEzNSwicGF0aCI6Ii8yOTA4OTM4OC8zNTI3NjU5NDUtNjE5MDE4OGMtYTVhZC00NzRkLWFhMjAtNzk2ZDZjYWU0YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDA2MjIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNjE3ZTE3NzM3MTE5MjZjZmVkMDg2Y2NmNjBkYTk4Y2YxMTc1YTljODI1ZjM4ZTM2ZmI3YTYxNWVkZGJhNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sdxsYr_icb20-kKkUi13oxlylkWZB8MKNq_kSLk_AlE)
> 
> .

Should be fixed now.
Thank you for the feedback!

**Comment by pzhlkj6612** [comment]
> > It works! However, Google's ads occupy some space on the paper. Is there a way to remove them when printing?
> 
> Should be fixed now.

I can confirm that those ads are not on the printed pages now.

![The screenshot of the clean paper](https://github.com/user-attachments/assets/ae113566-f845-44ae-8835-991a81953422)

.

**Comment by StakFallT** [comment]
This still doesn't work for me on Chromium on Linux; it's still the same effect; it looks like the browser shown by pzhlkj6612 is using Edge. As a result, I think this should be re-opened as the issue still persists.

Here's another screenshot of the print preview dialog with the attempted date / time:
![image](https://github.com/user-attachments/assets/54c2e2c4-4ab4-4660-8c54-afdc60bd972f)


I've tried setting the printer to my HP LaserJet P4014 to see if maybe the driver is causing the parsing issue, but that was the same effect. If it helps, I'm on Manjaro using Chromium. Here's the info from my Chromium browser's about page:

Chromium
Version 122.0.6261.69 (Official Build) Arch Linux (64-bit)

And here's the info from "inxi --system"
![image](https://github.com/user-attachments/assets/d41436ef-3b32-4e81-b79f-6ff40f3e6567)

From uname -a
Linux Fawkes1 5.17.15-1-MANJARO #1 SMP PREEMPT Wed Jun 15 07:09:31 UTC 2022 x86_64 GNU/Linux

From cat /etc/issue
Manjaro Linux \r  (\n) (\l)


No extensions installed on this Chromium user profile either (minus the one that comes with Chromium, and I tried turning that off to see if it had any difference, and it's still the same effect):
![image](https://github.com/user-attachments/assets/7de6732a-e47f-4dd0-8119-5789d0f672fd)

**Comment by pzhlkj6612** [comment]
> it looks like the browser shown by pzhlkj6612 is using Edge.

Yes, I was using Microsoft Edge on Linux and Windows.

> This still doesn't work for me on Chromium on Linux;

I'm using Google Chrome 127.0.6533.73 on Windows 11 and don't see the wrong layout:

![The screenshot of the printing dialog on Google Chrome on Windows 11](https://github.com/user-attachments/assets/9205feb4-4c5d-4693-86b2-132613c80b1a)

Maybe this is a Chromium-only defect?

.

**Comment by l9c** [comment]
check Background Graphics in More Settings @StakFallT

**Comment by StakFallT** [comment]
I just tried that and this was the result:
![image](https://github.com/user-attachments/assets/eed913a4-6e1c-48b5-ba82-bb5b2436f6fc)

For comparison (when setting it to my HP LaserJet P4014):
![image](https://github.com/user-attachments/assets/590a1dd4-613e-4b8b-8224-3e25440a464b)


Granted, it makes it easy to read due to the contrasted backgrounds on the various entries, but it's still not like what I see on the page (two columns)

**Comment by StakFallT** [comment]
> [pzhlkj6612](/pzhlkj6612)

I don't think it's a Chrome / Chromium issue, because I just tried it with Chrome Version 120.0.6099.216 (Official Built) (64-bit), FireFox (123.0 (64-bit) Mozilla Firefox for Manjaro Linux,  thinking maybe it's just Chromium, and Chrome and Firefox both also have the issue as well. I could try something like Opera, but I suspect the issue will be present there as well, and if it's not it would likely be something Opera would be doing to correct something.

**Comment by pzhlkj6612** [comment]
@StakFallT 

> but it's still not like what I see on the page (two columns)

The page size of "latter" is a bit small, please try the "A3" paper or use the "landscape" layout instead.

> I don't think it's a Chrome / Chromium issue

I think **I9c** is right. That's because of the "Background Graphics" setting.

**Comment by StakFallT** [comment]
I wasn't able to set it to A3 using my print driver, but I was able to using Save to PDF. I then opened the PDF in a reader and was able to get a preview of what I expected it should look like!   It seems the A3 thing was the culprit. Thanks!

**Comment by pzhlkj6612** [comment]
@StakFallT , don't forget to try the "landscape" layout.
